enum TextType {
  databaseOpenOperationSuccess('DATABASE_OPEN_OPERATION_SUCCESS'),
  databaseCloseOperationSuccess('DATABASE_CLOSE_OPERATION_SUCCESS'),
  databaseDeleteOperationSuccess('DATABASE_DELETE_OPERATION_SUCCESS'),
  databaseInsertRowOperationSuccess('DATABASE_INSERT_ROW_OPERATION_SUCCESS'),
  databaseUpdateRowOperationSuccess('DATABASE_UPDATE_ROW_OPERATION_SUCCESS'),
  databaseDeleteRowOperationSuccess('DATABASE_DELETE_ROW_OPERATION_SUCCESS'),
  databaseTable('DATABASE_TABLE'),
  applicationName('APPLICATION_NAME'),
  settings('SETTINGS'),
  languages('LANGUAGES'),
  english('ENGLISH'),
  turkish('TURKISH'),
  themes('THEMES'),
  lightTheme('LIGHT_THEME'),
  darkTheme('DARK_THEME'),
  dragAndDropObfuscationFile('DRAG_AND_DROP_OBFUSCATION_FILE'),
  dragAndDropDependencyFolder('DRAG_AND_DROP_DEPENDENCY_FOLDER'),
  noResultsFound('NO_RESULTS_FOUND'),
  obfuscationFile('OBFUSCATION_FILE'),
  dependencyFolder('DEPENDENCY_FOLDER'),
  clear('CLEAR'),
  start('START'),
  back('BACK'),
  cancel('CANCEL'),
  refresh('REFRESH'),
  line('LINE'),
  errors('ERRORS'),
  noErrorsFound('NO_ERRORS_FOUND'),
  noSuchDependencyFound('NO_SUCH_DEPENDENCY_FOUND'),
  dependencyNeverMentionedInObfuscationFile('DEPENDENCY_NEVER_MENTIONED_IN_OBFUSCATION_FILE'),
  details('DETAILS'),
  className('CLASS_NAME'),
  methodName('METHOD_NAME'),
  statusCode('STATUS_CODE'),
  localizedMessage('LOCALIZED_MESSAGE'),
  stackTrace('STACK_TRACE'),
  exceptionMessage('EXCEPTION_MESSAGE'),
  date('DATE'),
  logDetails('LOG_DETAILS'),
  close('CLOSE'),
  cookies('COOKIES'),
  webCertificateHasBeenTrustedSuccessfully('WEB_CERTIFICATE_HAS_BEEN_TRUSTED_SUCCESSFULLY'),
  storageAccessPermissionRequestTitle('STORAGE_ACCESS_PERMISSION_REQUEST_TITLE'),
  storageAccessPermissionRequestExplanation('STORAGE_ACCESS_PERMISSION_REQUEST_EXPLANATION'),
  openSettings('OPEN_SETTINGS');

  final String name;

  const TextType(this.name);
}
