name: obfuscation_controller
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Localization
    sdk: flutter
  font_awesome_flutter: ^10.7.0 # Application Icons
  flutter_riverpod: ^2.5.1 # State Management
  equatable: ^2.0.5 # Object Comparison
  go_router: ^14.1.4 # Routing
  lottie: ^3.1.2 # Lottie Animations
  shared_preferences: ^2.2.3 # Shared Preferences
  desktop_drop: ^0.4.4 # Drag & Drop
  scrollable_positioned_list: ^0.3.8 # Positioned List
  dio: ^5.4.3+1 # Http Client
  cookie_jar: ^4.0.8 # Cookie Management
  dio_cookie_manager: ^3.1.1 # Cookie Management
  encrypt: 5.0.1 # Encryption/Decryption
  crypto: ^3.0.3 # Hashing Algorithms
  connectivity_plus: ^6.0.3 # Internet Connection
  image_picker: ^1.1.2 # Picks Images From Gallery
  file_picker: ^8.0.3 # Picks Files From Documents and Downloads
  open_filex: ^4.4.0 # Opens Files
  mime: ^1.0.5 # Mime Types For Downloading Files
  path_provider: ^2.1.3 # Path Provider
  sqflite: ^2.3.3+1 # Local Data Storage
  permission_handler: ^11.3.1 # Permission Management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/lottie/
  - assets/translations/
